#24 Feat/snutt
wafflestudio/waffledotcom-web pull request #25
Opened 2023-04-08 03:24 UTC by hitkoo

## 태스크 URL

## 관련 이슈 (Optional)

## 체크리스트
- [ ] PR 제목에 관련 issue 번호 추가
- [ ] pre-commit 성공 여부
- [ ] yarn build 성공 엽
- [ ] Type label 추가

## 설명

## 테스트 방법 (Optional)

## 기타 질문 및 공유 사항 (Optional)

2023-04-08 08:52 UTC, minkyu97 commented
저희 `components` 디렉토리의 구조를 보면 `Service` 폴더가 만들어져있는데요, 새로 만든 서비스 페이지 관련 컴포넌트 여기로 이동시켜주세요

2023-04-08 08:53 UTC, minkyu97 commented
그리고 컴포넌트 폴더들의 이름은 기존에 파스칼 케이스를 사용하고 있었는데, 고유명사이긴 하지만 굳이 SNUTT 로 갈 필요가 있을까요? 다른 분들 의견 좀요.
@designDefined @joongwon @iihyungsuk

2023-04-08 08:55 UTC, joongwon commented
전 고유명사 존중합니다

2023-04-08 09:55 UTC, hitkoo commented
> 저희 `components` 디렉토리의 구조를 보면 `Service` 폴더가 만들어져있는데요, 새로 만든 서비스 페이지 관련 컴포넌트 여기로 이동시켜주세요

저 서비스가 메인페이지중 하나 이름을 서비스로 해둔것같던데 아닌가요??

2023-04-08 10:39 UTC, minkyu97 commented
> 저 서비스가 메인페이지중 하나 이름을 서비스로 해둔것같던데 아닌가요??

아 그러네
폴더 구조를 depth를 나눠야되겠는데요?? 지금은 너무 정신없어서

2023-04-08 11:11 UTC, hitkoo commented
> > 저 서비스가 메인페이지중 하나 이름을 서비스로 해둔것같던데 아닌가요??
> 
> 아 그러네
> 폴더 구조를 depth를 나눠야되겠는데요?? 지금은 너무 정신없어서

그럼 기존 service 폴더를 ServiceSum 으로바꾸고 Service 폴더판뒤 그안에 새컴포넌트넣을게

2023-04-08 12:25 UTC, minkyu97 commented
> 그럼 기존 service 폴더를 ServiceSum 으로바꾸고 Service 폴더판뒤 그안에 새컴포넌트넣을게
ServiceSum 이 뭐지?? 서비스합? ServiceSummary의 약자??
만약 약자라면 안 줄이는 게 나을듯

2023-04-09 04:10 UTC, hitkoo commented
> > 그럼 기존 service 폴더를 ServiceSum 으로바꾸고 Service 폴더판뒤 그안에 새컴포넌트넣을게
> 
> ServiceSum 이 뭐지?? 서비스합? ServiceSummary의 약자??
> 만약 약자라면 안 줄이는 게 나을듯 (그리고 사실 동일 depth에 존재하는 게 아니면 디렉토리명 겹쳐도 괜찮을 것 같기도하고)
> 그리고 내가 폰으로 보느라 디렉토리 구조를 착각했는데
> 현재 구조는 이렇게 되어있잖아
> ```
> components/ 각종 컴포넌트 모음
>   ┣ common/ 공통 컴포넌트 모음
>   ┣ default/ ??
>   ┣ Home/ 소개 페이지
>   ┣ Member/ 멤버 페이지
>   ┖ Recruit/ 리크루팅 페이지
> ```
> 
> 근데 넌 지금 이렇게 추가했는데
> 
> ```
> components/ 각종 컴포넌트 모음
>   ┣ common/ 공통 컴포넌트 모음
>   ┣ default/ ??
>   ┣ Home/ 소개 페이지
>   ┣ Member/ 멤버 페이지
>   ┣ Recruit/ 리크루팅 페이지
>   ┣ ServiceIntroduce/ 서비스 소개 컴포넌트
>   ┖ SNUTT/ SNUTT 컴포넌트
> ```
> 
> 내가 보기엔 이게 맞는 것 같은데 어떻게 생각해?
> 
> ```
> components/ 각종 컴포넌트 모음
>   ┣ common/ 공통 컴포넌트 모음
>   ┣ default/ ??
>   ┣ Home/ 소개 페이지에서 사용하는 컴포넌트들
>   ┣ Member/ 멤버 페이지에서 사용하는 컴포넌트들
>   ┣ Recruit/ 리크루팅 페이지에서 사용하는 컴포넌트들
>   ┖ Service/ 서비스 페이지에서 사용하는 컴포넌트들
>       ┣ common/ 서비스 페이지에서 공통으로 사용하는 컴포넌트들
>           ┖ ServiceIntroduce/ 서비스 소개 컴포넌트
>       ┣ SNUTT/ SNUTT 컴포넌트
>       ┣ Siksha/ 식샤 컴포넌트 (추가 예정)
>       ┖ Snuboard/ 스누보드 컴포넌트 (추가 예정)
> ```

무조건 이게 맞넹 저렇게할게

2023-04-10 14:16 UTC, iihyungsuk commented
Introduce~~와 description의 이름이 통일되면 좋을 것 같아요. 
태그 className은 description이니까 
1. 해당 태그 내부 요소도 IntroduceHead, IntroduceCarousel 대신 DecriptionHead, DescriptionCarousel로 통일
2. description className을 introduce으로 변경

+ Introduce가 들어가는 변수명 및 함수명 등도 Introduce가 아니라 Introduction이면 좋을 것 같습니다.

2023-04-10 14:23 UTC, iihyungsuk commented
css에서는 camelCase보다 하이픈을 구분자로 사용하는 게 일반적이라고 알고 있는데 기존 코드에서 특별히 className들을 camelCase로 사용하고 있는 이유가 있나요? @minkyu97 @joongwon @designDefined

2023-04-10 14:29 UTC, joongwon commented
css 모듈 쓰면 styles.camelCaseName 으로 접근하는 게 styles["kebab-case-name"] 보다 편해서 그렇습니다.

2023-04-10 14:31 UTC, iihyungsuk commented
> css 모듈 쓰면 styles.camelCaseName 으로 접근하는 게 styles["kebab-case-name"] 보다 편해서 그렇습니다.

아하 넵 감사합니다!

2023-04-10 14:32 UTC, joongwon commented
근데 cx로 다 감쌀거면 의미 없긴 하네요. 지금은 그냥 컨벤션인듯 합니다.

2023-04-10 14:41 UTC, minkyu97 commented
지금은 둘을 혼용해서 쓰고 있는데, 언제 한 번 날잡고 하나로 컨벤션을 통일시키면 좋겠네요.

2023-04-11 18:16 UTC, minkyu97 approved these changes
고생했으
캐러셀은 같이 고민해봅시다

2023-04-12 04:53 UTC, iihyungsuk commented
> 그리고 컴포넌트 폴더들의 이름은 기존에 파스칼 케이스를 사용하고 있었는데, 고유명사이긴 하지만 굳이 SNUTT 로 갈 필요가 있을까요? 다른 분들 의견 좀요. @designDefined @joongwon @iihyungsuk

뒤늦게 죄송합니다. 개인적으로 그냥 파스칼케이스를 사용하는 게 더 통일성 있는 것 같아요.

2023-04-12 05:04 UTC, hitkoo commented
혹시모를일이니 통일성 유지하여 SNUTT > Snutt 로 수정하고 merge 넣겠습니다

2023-04-12 05:41 UTC, iihyungsuk commented
뒤늦게 죄송합니다. 페이지 위아래 부분이 잘립니다. 디스플레이 크기 차이인 거 같은데 제 노트북 디스플레이 크기 상에서는 잘려서 나오는 거 같아요. 

실제 브라우저를 사용할 때는 브라우저 상하단 인터페이스 때문에 약 713px 정도밖에 되지 않는데(윈도우 크롬 기준)
Figma에서는 전체 대지 높이가 1080px이고 이 크기에 기반해서 내부 요소들의 높이가 상수값으로 정해져서
height가 상수값으로 정해진 해당 요소들의 height와 gap의 총합이 713px를 초과해버려서 그런 거 같아요.
 
Figma 대지 크기를 바꾸거나 비율 생각해서 상수값으로 설정된 height css를 바꿔야 할 거 같아요. 

![기본 화면](https://user-images.githubusercontent.com/105846051/231357264-ec091c7a-7bca-4d12-83c6-86824922dfe2.png)

2023-04-12 05:52 UTC, iihyungsuk commented on components/Service/SNUTT/SNUTT.module.scss
> +  @include position.home-container;
![image](https://user-images.githubusercontent.com/105846051/231362253-bc9bc3b4-0f57-4539-b67c-477552d1eeb1.png)
해당 라인 때문에 "min-height:100vh" 스타일이 들어가는데, 굳이 따지자면 그냥 "height:100vh"가 더 적합한 것 같습니다.
include 제거하고 관련 속성들 직접 입력하면 더 좋을 거 같아요.

2023-04-12 05:54 UTC, hitkoo commented
> 뒤늦게 죄송합니다. 페이지 위아래 부분이 잘립니다. 디스플레이 크기 차이인 거 같은데 제 노트북 디스플레이 크기 상에서는 잘려서 나오는 거 같아요. 
> 
> 실제 브라우저를 사용할 때는 브라우저 상하단 인터페이스 때문에 약 713px 정도밖에 되지 않는데(윈도우 크롬 기준)
> Figma에서는 전체 대지 높이가 1080px이고 이 크기에 기반해서 내부 요소들의 높이가 상수값으로 정해져서
> height가 상수값으로 정해진 해당 요소들의 height와 gap의 총합이 713px를 초과해버려서 그런 거 같아요.
>  
> Figma 대지 크기를 바꾸거나 비율 생각해서 상수값으로 설정된 height css를 바꿔야 할 거 같아요. 
> 
> ![기본 화면](https://user-images.githubusercontent.com/105846051/231357264-ec091c7a-7bca-4d12-83c6-86824922dfe2.png)
> 

아직 기초적인 실수도 많을테니 코멘트는 언제나 감사합니다.
제 노트북이나 데스크탑환경에서는 확인 못했던부분이라 height도 해상도 대응되도록 수정하겠습니다

2023-04-12 06:05 UTC, kiwidebruyne commented on components/Service/SNUTT/SNUTT.module.scss
> +  }
윗부분에 $block1~7 의 map 변수를 이미 반복적으로 선언했는데 style 부분에서도 또 반복적인 코드가 나열된 게 더 효율적으로 짜고 싶다는 욕심이 개인적으로 막 드네요..

$block1~7을 배열로 묶어서,
top, bottom, width, height 속성값까지 위 $block map에 포함시킨 채로 선언하고 [sass 반복문](https://inpa.tistory.com/entry/SCSS-%F0%9F%92%8E-%EC%A1%B0%EA%B1%B4%EB%AC%B8-%EB%B0%98%EB%B3%B5%EB%AC%B8)으로 작성할 수 있을 거 같아요.

아무튼 반복되는 부분은 하나만 작성해서 짤 수 있을 거 같은데 사실 저도 sass 문법을 잘 몰라서 어떤 형태가 제일 깔끔할지 모르겠네요..

2023-04-12 06:16 UTC, iihyungsuk commented on components/Service/SNUTT/SNUTT.module.scss
> +    }
이 부분도 마찬가지 생각입니다.

2023-04-12 08:26 UTC, hitkoo commented on components/Service/SNUTT/SNUTT.module.scss
> +  }
반영했습니다! 저도 이제 제일 깔끔한건지 확신이 안서지만 그래도 형석님 덕분에 구조&가독성이 훨씬 좋아진 것 같습니다. 감사합니다.

2023-04-13 05:35 UTC, iihyungsuk requested changes
수고하셨습니다! 다만 전체적으로 scss에서의 너비/높이/폰트크기/gap 등이 전체적으로 Figma에서의 비율이나 크기와 일치하지 않는 경향이 있는데 개인적으로 최대한 정확하게 맞추면 좋을 거 같아요.

2023-04-13 05:35 UTC, iihyungsuk commented on components/Service/Snutt/Snutt.module.scss
> +      width: 10vmin;
Figma상에서는 100vmin = 1080px
blockline에 해당하는 블럭 하나의 너비 180px인데

1. 기존의 width가 왜 180px가 아니라 120px였는지
2. 피그마상에서 10vmin = 108px. 기존 120px랑 불일치.

Figma상의 비율이랑 다른 거 같은데 혹시 특별한 이유가 있나요?

2023-04-13 05:35 UTC, iihyungsuk commented on components/Service/Snutt/Snutt.module.scss
> +      gap: 1vmin;
여길 vmin으로 바꾼 건 진짜 좋은 거 같아요!

2023-04-13 05:35 UTC, iihyungsuk commented on components/Service/common/IntroductionCarousel/IntroductionCarousel.module.scss
> +  margin-top: 2vmin;
11번 라인도 9번 라인처럼 계산하면 좋을 것 같아요.

2023-04-13 05:35 UTC, iihyungsuk commented on components/Service/common/IntroductionCarousel/IntroductionCarousel.module.scss
> +  gap: 1.5vmin;
마찬가지로 변환 계산 과정에 관한 의문.

2023-04-13 05:35 UTC, iihyungsuk commented on components/Service/common/IntroductionHead/IntroductionHead.module.scss
> +  width: calc(100vmin / 1080 * 840);
기존 870px가 아니라 840을 쓰는 이유가 있나요?

2023-04-13 05:35 UTC, iihyungsuk commented on components/Service/common/IntroductionHead/IntroductionHead.module.scss
> +  gap: 2vmin;
위와 동일 의견.

2023-04-13 05:35 UTC, iihyungsuk commented on components/Service/common/IntroductionHead/IntroductionHead.module.scss
> +      height: 1.3em;
height가 반 이상이나 줄게 된 이유가 있나요?

2023-04-13 05:35 UTC, iihyungsuk commented on components/Service/common/IntroductionHead/IntroductionHead.module.scss
> +      font-size: 1.6em;
더 정확한 비율의 값 사용 요망

2023-04-13 05:35 UTC, iihyungsuk commented on components/Service/common/IntroductionHead/IntroductionHead.module.scss
>        align-items: flex-end;
위와 동일 의견

2023-04-13 05:35 UTC, iihyungsuk commented on components/Service/common/IntroductionHead/IntroductionHead.module.scss
> +    top: 2.7vmin;
위와 동일 의견

2023-04-14 09:37 UTC, hitkoo commented on components/Service/Snutt/Snutt.module.scss
> +      width: 10vmin;
이건 디자이너의 원래 의도는 좌 / 가운데 / 우 나눠서 짜는거였는데 16:9 아닌 다른 해상도까지 고려했을 때 백 / 메인으로 나눈뒤  백위에 메인이 뜨게 하는 식으로 짜는게 나을 것 같다고 얘기했었고, 그러면서 조금 수정했습니다!
근데 어쨌든 반응형으로 짜는 과정에서 디테일이 부족한건 있었고 최종적으로는1920x1080 기준 160px로 짰습니다!

2023-04-14 09:43 UTC, hitkoo commented
> 수고하셨습니다! 다만 전체적으로 scss에서의 너비/높이/폰트크기/gap 등이 전체적으로 Figma에서의 비율이나 크기와 일치하지 않는 경향이 있는데 개인적으로 최대한 정확하게 맞추면 좋을 거 같아요.

지금까지 디자이너와 협업한 적이 없어서, 그냥 눈대중으로 짜는 버릇이 들어서 디테일한 부분을 안 챙겼던 것 같습니다 ㅠㅠ
형석님 꼼꼼한 리뷰덕에 pc환경에서 고정px를 반응형으로 짜는 법 많이 생각해보고 조금은 깨달았네요 ㅎㅎ 감사합니다.
그리고 이제 기억 났는데 세미나 5주차 peer review때도 형석님이 제 과제 리뷰하셨었네요.. 항상 꼼꼼한 리뷰 감사하고 그에 상응하는 결과물 만들도록 노력하겠습니다ㅎㅎ

2023-04-15 05:19 UTC, iihyungsuk commented
> 지금까지 디자이너와 협업한 적이 없어서, 그냥 눈대중으로 짜는 버릇이 들어서 디테일한 부분을 안 챙겼던 것 같습니다 ㅠㅠ 형석님 꼼꼼한 리뷰덕에 pc환경에서 고정px를 반응형으로 짜는 법 많이 생각해보고 조금은 깨달았네요 ㅎㅎ 감사합니다. 그리고 이제 기억 났는데 세미나 5주차 peer review때도 형석님이 제 과제 리뷰하셨었네요.. 항상 꼼꼼한 리뷰 감사하고 그에 상응하는 결과물 만들도록 노력하겠습니다ㅎㅎ

헉 아닙니다 승진님이 introduction을 컴포넌트로 짜주셔서 사실 제가 할 일이 그리 많지 않아서.. 코드리뷰라도 열심히 해야죠! 저야말로 항상 감사합니다 !

2023-04-15 05:21 UTC, iihyungsuk approved these changes
css만 간단하게 다시 한번 봤습니다! 수고하셨습니다 !! 코드가 야무지네요

2023-04-15 05:21 UTC, kiwidebruyne commented on components/Service/Snutt/Snutt.module.scss
> +  @include position.home-container;
기존 스크롤 애니메이션 컴포넌트들 .container 스타일에 `position.home-container` 스타일 묶음이 다 @include되어 있던데 혹시 해당 스타일 묶음에 `height: 100vh` 대신 `min-height: 100vh`가 들어가 있는 이유가 무엇인가요?
@minkyu97 @joongwon  @designDefined 

이 부분에서는 `position.home-container`에 있는 `min-height: 100vh`가 이 불필요한 속성인 거 같아서 include 대신 직접 필요한 스타일들만 짜주는 게 좋을 거 같아요

2023-04-15 05:21 UTC, kiwidebruyne commented on components/Service/Snutt/Snutt.module.scss
> +  @include position.flex-center;
container 요소 내부에 싸여있는 `background`와 `introduction` 두 요소 모두 너비높이 100vh, 100vw이고 `position: fixed`에 `top: 0; left: 0;`으로 위치까지 지정되어있어서 중앙정렬이 필요없으므로 위 100번 라인 지워도 괜찮을 것 같습니다.

2023-04-15 05:21 UTC, kiwidebruyne commented on components/Service/Snutt/Snutt.module.scss
> +.available {
그냥 가독성 측면에서 
`.container.available {` 이렇게 둘 다 적어주면 좋을 거 같은데 혹시 어떻게 보시나요?

2023-04-15 05:21 UTC, kiwidebruyne commented on styles/_color.scss
> +$SNUTT-block7: #af56b3;
고유명사 대소문자 여부를 어떻게 할지 확실하게 정해야 할 거 같아요! 
개인적으로 저는 다른 데에서는 몰라도 css에서는 대문자 사용은 최대한 안 하는 게 좋은 거 같아요. 여기는 케밥케이스라서 더더욱이요!

위 35~37번 라인에서 QnA도 qna로 바꿔도 괜찮을까요?
@minkyu97 @joongwon @designDefined

2023-04-15 05:21 UTC, kiwidebruyne commented on components/Service/Snutt/Snutt.module.scss
> +    }
`.blockLine`을 `.lineWrap` 안으로 안 넣어줄 이유가 없다고 생각합니다!

2023-04-15 05:21 UTC, kiwidebruyne commented on components/Service/Snutt/Snutt.module.scss
> +  // block1
이 index 주석들 짱이네요

2023-04-15 05:21 UTC, kiwidebruyne commented on components/Service/Snutt/Snutt.module.scss
> +  transition: 0.5s ease;
현재 transition은 지정되어있는데 아무런 애니메이션도 지정되지 않은 거 같아요! 삭제해도 될 거 같습니다.

2023-04-15 05:21 UTC, kiwidebruyne commented on components/Service/Snutt/Snutt.module.scss
> +}
`.container`에만 `opacity` 애니메이션 넣고 `.background`, `.introduction`에서 `opacity`, 'visibility` 속성 빼면 코드가 좀 간단해질 거 같아요. 
```css
.container {
  transition: 0.5s;
  opacity: 0;
  . .
}

.container.available {
  opacity: 1;
  . .
}
```

2023-04-15 07:54 UTC, hitkoo commented on components/Service/Snutt/Snutt.module.scss
> +.available {
저렇게 하면 css가 덮이는건지 그냥 컴포넌트가 싹 사라져서
available 위에 "when scrollState "available" is true" 라고 주석달았습니다.

2023-04-15 07:58 UTC, iihyungsuk commented on components/Service/Snutt/Snutt.module.scss
> +.available {
앗 아까 해봤을 때는 되던데 혹시 .container랑 .available 사이에 띄어쓰기 있나요?

2023-04-15 15:54 UTC, hitkoo commented on components/Service/Snutt/Snutt.module.scss
> +.available {
아 띄어쓰기를 했었네요
반영했습니다! carousel animation관련 작업하던게 add 들어가있어서 commit은 나중에 하겠습니당

2023-04-16 16:15 UTC, minkyu97 commented on styles/_color.scss
> +$SNUTT-block7: #af56b3;
애매하게 하느니 하나로 통일하는 게 좋겠네요
스누보드 PR 올릴 때 그렇게 바꿔주세요~

2023-04-18 16:09 UTC, minkyu97 commented
@hitkoo 고생했다 머지해도 돼!
@iihyungsuk 둘 다 리뷰 꼼꼼히 하느라 고생 많았어~

2023-04-18 22:36 UTC, merged