식샤 서비스 소개 페이지 개발
wafflestudio/waffledotcom-web pull request #26
Opened 2023-04-18 16:40 UTC by minkyu97

## 태스크 URL
https://www.notion.so/wafflestudio/49d18117949f4387a316dd6dd5e4fe12?p=81db745055074db1abc0fc7deccccf80&pm=s

## 관련 이슈 (Optional)

## 체크리스트
- [x] PR 제목에 관련 issue 번호 추가
- [ ] pre-commit 성공 여부
- [x] yarn build 성공 여부
- [x] Type label 추가

## 설명
식샤 서비스 소개 페이지입니다.
슬랙 스레드에 [애니메이션 작동 영상](https://wafflestudio.slack.com/archives/C01KGJSRPRC/p1681835576588359) 올려놓았으니 확인해주세요~

## 테스트 방법 (Optional)

## 기타 질문 및 공유 사항 (Optional)

2023-04-30 04:07 UTC, designDefined approved these changes
확인했습니다~ 질문 몇 개 달아놨는데 뭐 괜찮은듯

2023-04-30 04:07 UTC, designDefined commented on components/Service/Snutt/Snutt.tsx
> +      toggleState(0.75, 2.7, "available");
요거 낮춘 이유가 무엇인가요?
혹시 스크롤 훅의 수정이 필요한가 해서유

2023-04-30 04:07 UTC, designDefined commented on components/Service/Siksha/Siksha.module.scss
> +    }
이 부분은 그라데이션을 자연스럽게 하기 위해 추가한 부분인가요???

2023-04-30 04:07 UTC, designDefined commented on components/Service/Siksha/Siksha.module.scss
> +    }
![image](https://user-images.githubusercontent.com/82145088/235335001-7f753074-2f66-4922-a0f3-3b800a9d26d6.png)
좀 작은 해상도의 화면에서 숟가락/젓가락 가운데가 조금 안 맞아서 아쉬워용
뭐 사소하긴 함

2023-04-30 07:43 UTC, joongwon requested changes

2023-04-30 07:43 UTC, joongwon commented on components/Service/Siksha/Siksha.tsx
> +          </svg>
이거 svg 파일로 빼주는 게 좋겠습니다. 아래에 젓가락도 마찬가지.

2023-04-30 07:43 UTC, joongwon commented on components/Service/Siksha/Siksha.tsx
> +          <div className={cx("chopsticks", "chopsticks2")}>
chopsticks와 chopsticks2는 뭔가요?

2023-05-01 05:42 UTC, iihyungsuk requested changes
수고하셨습니다!

2023-05-01 05:42 UTC, iihyungsuk commented on components/Service/Siksha/Siksha.module.scss
> +  top: 1080px;
회의 때 이야기한 대로 두 줄 제거하면 될 것 같습니다.

2023-05-01 05:42 UTC, iihyungsuk commented on components/Service/Siksha/Siksha.module.scss
> +    align-items: center;
styles/_position.scss의 `flex-center` mixin use하면 좋을 것 같습니다.

2023-05-01 05:42 UTC, iihyungsuk commented on components/Service/Siksha/Siksha.module.scss
> +  }
현재 코드에서 아무런 기능도 하지 않고 있는 부분인 것 같은데 혹시 의도하신 게 있을까요?

2023-05-01 05:51 UTC, minkyu97 commented on components/Service/Snutt/Snutt.tsx
> +      toggleState(0.75, 2.7, "available");
회의 때 말한 거라 스킵하겠슴다 3으로 복구함

2023-05-01 05:52 UTC, minkyu97 commented on components/Service/Siksha/Siksha.module.scss
> +    }
그라데이션은 transition 적용이 안 돼서 사용한 꼼수임
2개의 배경을 겹쳐놓고 위에 있는 배경의 투명도를 바꾸는 식으로

2023-05-01 06:00 UTC, minkyu97 commented on components/Service/Siksha/Siksha.tsx
> +          <div className={cx("chopsticks", "chopsticks2")}>
디버깅용 코드.. 지우겠씁니다

2023-05-01 06:06 UTC, minkyu97 commented on components/Service/Siksha/Siksha.module.scss
> +  }
gradient 에 transition을 줄 수 없어서 비슷하게나마 구현해보려고 사용한 꼼수임다
30번 라인에 `::before` 의 색상은 black 같이 눈에 띄는 걸로 바꿔보면 어떤 효과를 주려고 했던 것인지 알 수 있을 듯

2023-05-01 06:30 UTC, minkyu97 commented on components/Service/Siksha/Siksha.module.scss
> +    }
이게 지금보니까 피그마에서부터 좀 치우쳐져 있네요.. 좀 가운데로 수정하겠습니다

2023-05-01 06:32 UTC, iihyungsuk commented on components/Service/Siksha/Siksha.module.scss
> +  }
아하 그렇군요 감사합니다

2023-05-01 07:38 UTC, minkyu97 commented on components/Service/Siksha/Siksha.module.scss
> +    align-items: center;
반영 완료

2023-05-01 07:38 UTC, minkyu97 commented on components/Service/Siksha/Siksha.tsx
> +          <div className={cx("chopsticks", "chopsticks2")}>
반영 완료

2023-05-01 07:38 UTC, minkyu97 commented on components/Service/Siksha/Siksha.tsx
> +          </svg>
반영 완료

2023-05-01 07:38 UTC, minkyu97 commented on components/Service/Siksha/Siksha.module.scss
> +    }
반영 완료

2023-05-01 07:38 UTC, minkyu97 commented on components/Service/Snutt/Snutt.tsx
> +      toggleState(0.75, 2.7, "available");
반영 완료

2023-05-13 05:52 UTC, minkyu97 commented
@iihyungsuk @joongwon 혹시 더 리뷰하실 사항 있으면 말씀해주시고 아니면 approve 해주세요~!

2023-05-13 09:15 UTC, joongwon approved these changes
lgtm

2023-05-17 07:11 UTC, iihyungsuk approved these changes
에구 늦어서 죄송합니다. 수고하셨습니다!

2023-05-18 12:34 UTC, merged