Feat/home main about
wafflestudio/waffledotcom-web pull request #31
Opened 2023-05-17 08:46 UTC by designDefined

## 태스크 URL
[소개 1~2 페이지](https://www.notion.so/wafflestudio/v2-5-1-2-ad1ea97a28304b3d9ef9ccbecf3f7211)

## 관련 이슈 (Optional)

## 체크리스트
- [ ] pre-commit 성공 여부
- [ ] yarn build 성공 여부
- [x] Type label 추가

## 설명
- 소개 1~2페이지 작업했습니다
- 역시 `/newHome ` 에서 확인 가능하며 컴포넌트도 newHome 폴더에다가 따로 모아놨습니다. 스크럼 때 어떤 식으로 컴포넌트 정리할 지 확정되면 반영하도록 하겠습니다
- 스크롤 훅 적용해보았습니다

## 테스트 방법 (Optional)
`https://localhost:3000/newHome`

## 기타 질문 및 공유 사항 (Optional)
- 헤더와 2페이지(About) 관련 디자인 문의사항 있습니다
- 스크롤 훅 사용 방식도 대충 통일시켜야 할 것 같네요
- 지금 다음 화면으로 넘기려면 스크롤을 꽤 내려야 하는데, 이 스크롤 내림 정도도 커스터마이징하면 좋을 것 같습니다 (어렵지 않게 가능할 듯). 다음과 같은 옵션이 있을 것 같습니다.
  - 지금 정도 (100vh)
  - 지금보다 줄이기
  - 조금이라도 스크롤 다운 되면 넘어가기 (애니메이션 중에는 스크롤 안 됨)

2023-05-17 08:47 UTC, designDefined commented
커밋 확인하기 좋게 `feat/home-header`로 베이스 변경했습니다

2023-05-22 08:25 UTC, designDefined commented
일단 고칠부분 다 고쳐놓긴 했습니다 이제 스크롤 훅 작업할게요

2023-05-28 13:39 UTC, minkyu97 requested changes
다 좋은데 옆에 네비게이터 눌렸을 때 위로 올라갈 땐 빠릿빠릿한데 내려갈 땐 좀 딜레이가 길어요 ㅠ
`scrollIntoView` 함수의 behavior 을 auto 로 바꾸거나 해야될 것 같아요

2023-05-28 13:39 UTC, minkyu97 commented on components/newHome/Main/Main.tsx
> +      </div>
viewport의 width 나 height 이 일정 이상 커지면 여백이 생기네요 ㅠ

2023-05-28 13:39 UTC, minkyu97 commented on styles/font.scss
> +
얘네는 ttf 파일 따로 안 넣고 url 로 받아오는 이유가 있을까요??
어떤 게 더 좋은지 잘 모르겠긴한데 다른 것도 하나로 통일하는 게 좋을 것 같아서요

2023-05-29 09:12 UTC, designDefined commented on components/newHome/Main/Main.tsx
> +      </div>
배경 폰트 크기를 px2vh 이용하게 해서 큰사이즈에도 대응하게 했습니다~
위아래폭이 줄어들면 양쪽 여백이 좀 생기긴 하는데 외관상 vh 연동이 더 직관적인 것 같아서 요렇게 처리했슴다

2023-05-29 09:13 UTC, designDefined commented
scrollIntoView 동작 같은 경우에는 스크롤 라이브러리 고치면서 한번에 수정할게요!

2023-05-29 09:13 UTC, designDefined commented on styles/font.scss
> +
요건 어떤 방식이 더 좋을지 슬랙에서 얘기해보죠! 하나로 통일하는 게 좋긴 할듯요

2023-05-29 09:15 UTC, minkyu97 approved these changes

2023-06-16 12:38 UTC, merged