Feat/newhome-activity
wafflestudio/waffledotcom-web pull request #32
Opened 2023-05-17 18:34 UTC by hitkoo

## 태스크 URL

## 관련 이슈 (Optional)

## 체크리스트
- [ ] pre-commit 성공 여부
- [ ] yarn build 성공 여부
- [x] Type label 추가

## 설명

준영님 작업하신 feat/home-main-about branch base로 작업했습니다.

hover 관련 로직이 너무 짜치는데(이유는 모르겠지만 e.target.classList.add("hover") 가 안먹어서..)

피그마 보니까 이거 디자인 뭔가 엎을라는거 같으니 나중에 생각해보죠 ㅋㅋ

## 테스트 방법 (Optional)

## 기타 질문 및 공유 사항 (Optional)

2023-05-28 12:38 UTC, minkyu97 commented
`feat/home-main-about` 브랜치를 base로 작업한 건 좋은데 target branch 를 `main` 으로 바꿔서 다시 PR 올려주시기 바랍니다! 이렇게 하면 이 PR 이 종료되기 전까지 해당 브랜치를 머지할 수가 없어서요

2023-05-30 04:43 UTC, iihyungsuk requested changes
늦어서 죄송합니다. 수고하셨습니다.

2023-05-30 04:43 UTC, iihyungsuk commented on components/newHome/Activity/Activity.tsx
> +            <span>와플스튜디오에서 하는 활동들</span>
`span` 태그를 쓰신 이유가 따로 없다면 `p` 태그 쓰면 좋을 것 같습니다.
아니면 활동소개는 `h1` 태그, 아래 설명은 `p` 태그 쓰면 어떨까 싶습니다.

2023-05-30 04:43 UTC, iihyungsuk commented on components/newHome/Activity/Activity.tsx
> +          <div className={cx("textArea")}>
이번 회의 때 class name 형식 정하죠!
@hitkoo @minkyu97 @joongwon

2023-05-30 04:43 UTC, iihyungsuk commented on components/newHome/Activity/Activity.tsx
> +              </div>
`subTitleDataList` 같은 이름으로 데이터들을 object 배열에 모아놓은 다음 아래와 같이 짜는 건 어떨까요. 유지보수나 코드 가독성 면에서 더 좋을 것 같습니다.
```typescript
{subTitleDataList.map((data, idx) => (
  <div className={cx("subTitle", { active: index === idx })}>
    <div
      className={cx("head")}
      onClick={() => {
        setIndex(idx);
      }}
    >
      {data.title}
    </div>
    <div
      className={cx("detailDescription", {
        visible: index === idx,
      })}
    >
      {data.detailDescription}
    </div>
  </div>
))}
```

2023-05-30 04:43 UTC, iihyungsuk commented on components/newHome/Activity/Activity.module.scss
> +    justify-content: center;
styles/_position.scss에 관련 mixin 있습니다.

2023-05-30 04:43 UTC, iihyungsuk commented on components/newHome/Activity/Activity.module.scss
> +        }
`font-style: normal` 코드 불필요

2023-05-30 04:43 UTC, iihyungsuk commented on components/newHome/Activity/Activity.module.scss
> +        flex-direction: row;
58번 라인 불필요

2023-05-30 04:43 UTC, iihyungsuk commented on components/newHome/Activity/Activity.module.scss
> +          background-size: cover;
이 경우는 tsx에서 `img` 태그로 넣는 게 나을 것 같습니다.
[참고](https://chlolisher.tistory.com/77)

2023-05-30 04:43 UTC, iihyungsuk commented on components/newHome/Activity/Activity.module.scss
> +            overflow: hidden;
flex관련 내용 아무것도 필요없을 거 같아요

2023-05-30 04:43 UTC, iihyungsuk commented on components/newHome/Activity/Activity.module.scss
> +            font-style: normal;
위와 동일

2023-05-30 04:43 UTC, iihyungsuk commented on components/newHome/Activity/Activity.module.scss
> +  visibility: hidden;
이거 opacity: 0만 써도 되지 않나요?

2023-05-30 05:24 UTC, iihyungsuk commented
subtitle에 hover: cursor 속성도 넣어주세용

2023-06-16 13:18 UTC, hitkoo commented
a

2023-06-16 13:19 UTC, merged