Feat/home service member
wafflestudio/waffledotcom-web pull request #33
Opened 2023-05-20 08:46 UTC by iihyungsuk

## 태스크 URL
https://www.notion.so/wafflestudio/v2-5-3-4-0762387db68142e08b1c6d7460508f31?pvs=4

## 체크리스트
- [ ] pre-commit 성공 여부
- [x] yarn build 성공 여부
- [x] Type label 추가

## 설명
소개 3~4페이지 작업했습니다.
`components/newHome/Members`, `components/newHome/Services` 두 파일만 봐주시면 될 것 같습니다.

## 테스트 방법 (Optional)
https://localhost:3000/newHome

## 기타 질문 및 공유 사항 (Optional)
혹시 아래와 같이 원을 따라 애니메이션 적용되게 구현해보신 분 계실까요

![image](https://github.com/wafflestudio/waffledotcom-web/assets/105846051/1243e4f5-31a3-4333-969f-41753a4fc195)

마땅히 좋은 방법이 없는 거 같아서 현재는 원을 360등분한 1deg에 해당하는 호의 svg파일을 만들어 해당 svg 파일을 360개 넣고 각각 1deg, 2deg, 3deg, ...만큼 회전시켜둔 뒤 opacity를 조절하는 방법으로 구현했습니다.
```typescript
const result = [];
for (let i = 1; i <= 360; i++) {
  result.push(
    <div key={i} className={cx(`foreground-border-piece-index-${i}`)}>
      <Image
        src="/static/images/newHome/play_button_border_piece.svg"
        alt="border piece"
        width="29px"
        height="29px"
      />
    </div>,
  );
}
```

```scss
@for $i from 1 through 360 {
  > .foreground-border-piece-index-#{$i} {
    position: absolute;
    width: 29px;
    height: 29px;
    transition-duration: calc(3s / 360);
    transform: rotate(calc(1deg * ($i - 1)));
  }
}
```

근데 이렇게 했더니 화질이 상당히 깨져서 다른 방법을 찾아야 할 것 같은데 1deg짜리 호 svg 파일부터 360deg svg 파일까지 360개 svg 파일 만들어서 사용하는 방법 외에는 마땅히 떠오르질 않네요. 이것도 그리 좋은 방법은 아닌 거 같아서ㅜ 혹시 관련 아이디어나 경험 있으시면 말씀해주시면 감사하겠습니다.

2023-05-23 09:03 UTC, designDefined commented
확실하진 않지만 css circle fill animation으로 구글링해보니 비슷한 효과가 나오네요 
[css-gradient 2개 이용한 예시](https://codepen.io/txreplay/pen/aBVEow)
[clip 이용한 예시 1](https://codepen.io/kbeherec/pen/EEZYqv) 
[2](https://stackoverflow.com/questions/35383629/css-circle-border-fill-animation)

저도 정확한 원리는 모르겠어서 한 번 이쪽으로 서치해보세요!! 저도 공부 좀 해봐야겠습니다

2023-05-29 13:52 UTC, minkyu97 commented
준영님이 추천해주신 것 중에 `linear-gradient` 속성은 animation이나 transition 적용이 안 되는 걸로 알아서 원하는 효과를 주기는 어려울 것 같고요, `clip` 속성을 활용한 방법은 가능해보이긴 하는데 어차피 svg 파일을 사용할 거라면 `stroke-dashoffset`, `stroke-dasharray` 속성을 을 조절하는 animation 을 활용하는 것이 좋아보입니다.
참고 링크
- [dasharray 만을 이용한 애니메이션](https://stackoverflow.com/questions/72469814/how-to-implement-animation-on-stroke-dasharray-and-stroke-offset-circle-svg)
- [dasharray, dashoffset 을 모두 활용한 애니메이션](https://mong-blog.tistory.com/entry/svg%EA%B0%80-%EA%B7%B8%EB%A0%A4%EC%A7%80%EB%8A%94-%ED%9A%A8%EA%B3%BCwith-stroke-dasharray-stroke-dashoffset)

2023-05-30 06:59 UTC, iihyungsuk commented
두분 리뷰 달아주신 내용 참고해서 수정 후 push 했습니다!
승진이 형이 달아준 것처럼 stroke-dasharray 이용했습니다

2023-05-30 07:00 UTC, designDefined requested changes
수고하셨습니다! 애니메이션은 수정하시고 나면 다시 확인해보겠습니다

2023-05-30 07:00 UTC, designDefined commented on components/newHome/Members/Members.module.scss
> +
```suggestion
position:relative;
z-index: 100 // 100이 정확한 수치는 아니고, 한 번 통일시킬 필요는 있을 듯
```

이렇게 하면 컴포넌트가 off가 아닐 때 맨 위로 올라가게 되어서 다른 컴포넌트가 보이는 예상치 못한 에러를 방지할 수 있지 않을까 합니다. 컴포넌트마다 공통으로 이 설정을 적용해도 좋겠네요

2023-05-30 07:00 UTC, designDefined commented on components/newHome/Members/Members.tsx
> +                      상시 모집{"("}개발 실무 경험자{")"}
```suggestion
                      개발 실무 경험이 있을 경우 상시 모집
```
여기 문구 피그마와 다른 것 같습니다

2023-05-30 07:00 UTC, designDefined commented on components/newHome/Services/Services.tsx
> +function Carousel({
Carousel과 ProgressBox 컴포넌트는 파일을 분리하는 것도 괜찮을 것 같습니다 (가독성 때문에)

2023-05-30 07:00 UTC, designDefined commented on components/newHome/Services/Services.tsx
> +type TserviceData = {
```suggestion
type TServiceData = {
```
PascalCase 관련

2023-05-30 07:00 UTC, designDefined commented on components/newHome/Services/Services.tsx
> +const serviceDataArray: TserviceData[] = [
`serviceDataArray`는 좀 일반적인 명칭인 것 같아서, `serviceCarouselData`나 `serviceCarouselItemData`처럼 Carousel에서 사용된다는 힌트가 포함되게 작명되면 좀 더 좋지 않을까 합니다.
service 관련한 일반적인 데이터 더미를 만든 것이라면 파일을 분리해 놓는 것도 좋아 보이고요(이 부분은 팀적 논의가 필요할듯)

2023-05-30 07:00 UTC, designDefined commented on components/newHome/Services/Services.tsx
> +const serviceDataArrayLength: number = serviceDataArray.length;
length는 성능 최적화 때문에 따로 빼신 걸까요?
array.length는 메소드가 아니라 배열 내부에 따로 저장되어 있는 길이 데이터를 가져오는 방식이라, 사용시마다 length를 새로 계산하는 게 아니라 성능 저하가 딱히 일어나지 않는 걸로 알고 있습니다. 굳이 이런 문법을 사용할 필요가 있을까 하네요...!

length를 변수에 저장하는 것의 성능에 대해서는 사람들마다 의견이 좀 갈리는 것 같긴 하네요 [참고 1](https://stackoverflow.com/questions/9592241/javascript-is-the-length-method-efficient) [참고 2](https://stackoverflow.com/questions/17989270/for-loop-performance-storing-array-length-in-a-variable) [참고 3](https://www.codecademy.com/forum_questions/5286bae4548c35db2400242d)

2023-05-30 07:00 UTC, designDefined commented on components/newHome/Services/Services.tsx
> +function ProgressBox({
ProgressBox의 타이머 동작이, 매 슬라이드마다 5초짜리 타이머가 돌아가면서 사진 넘어가는 게 아니었나요?? 디자이너 분들과 한 번 확인해보는 게 좋을 듯

2023-05-30 07:00 UTC, designDefined commented on components/newHome/Services/Services.tsx
> +  };
지금 방식대로 할거면 이런 함수들은 useCallback으로 최적화하는 게 좋아보입니다

2023-05-30 07:00 UTC, designDefined requested changes
수고하셨습니다! 애니메이션은 수정하시고 나면 다시 확인해보겠습니다

2023-05-30 07:01 UTC, designDefined commented
> 수고하셨습니다! 애니메이션은 수정하시고 나면 다시 확인해보겠습니다

오 뭐야 애니메이션 수정하셨네요 요것도 확인해볼게요

2023-05-30 07:04 UTC, designDefined commented on components/newHome/Services/Services.tsx
> +function ProgressBox({
애니메이션 하시면서 수정하셨군요 확인했습니다!

2023-05-30 07:07 UTC, designDefined requested changes
타이머 작동 관련하여 간단한 의견 추가했습니다

2023-05-30 07:07 UTC, designDefined commented on components/newHome/Services/Services.tsx
> +  const [isPlaying, setIsPlaying] = useState<boolean>(false);
Service 컴포넌트가 화면에 보이면 자동으로 재생되고, 안보이게 되면 재생을 멈추는 게 성능과 UX상 좋지 않을까 합니다!

2023-05-30 07:07 UTC, designDefined requested changes
타이머 작동 관련하여 간단한 의견 추가했습니다

2023-05-30 07:10 UTC, minkyu97 commented on components/newHome/Services/Services.tsx
> +    }
이 부분에서 연산량이 많아서 로딩(회전) 애니메이션이랑 넘어가는 애니메이션 타이밍이 안 맞는 것 같아요
차라리 isPlaying이 해제되면 회전량을 초기화시키고 여기서는 3초에 한번씩 인덱스 증가시키는 걸로 바꾸면 어떨까요?
```suggestion
    if (isPlaying) {
      const interval = setInterval(() => {
        increaseIndex();
      }, 3000);
      return () => {
        clearInterval(interval);
      };
    }
```

2023-05-30 07:18 UTC, iihyungsuk commented on components/newHome/Services/Services.tsx
> +const serviceDataArrayLength: number = serviceDataArray.length;
아하 메소드랑 헷갈려서 빼두었는데 저장하지 않게 처리하겠습니다 감사합니다!

2023-05-30 07:20 UTC, iihyungsuk commented on components/newHome/Services/Services.tsx
> +  };
useCallback 처리하였습니다 감사합니다!

2023-05-30 07:33 UTC, iihyungsuk commented on components/newHome/Services/Services.tsx
> +  const [isPlaying, setIsPlaying] = useState<boolean>(false);
반영했습니다!

2023-05-30 07:50 UTC, iihyungsuk commented on components/newHome/Services/Services.tsx
> +    }
일단 단위 5=> 50으로 수정했습니다. 다시한번 확인해주실 수 있을까요? 연산량이 많은 게 문제되면 말씀해주신 대로 바꾸는 게 나을 듯

2023-05-30 07:52 UTC, iihyungsuk commented on components/newHome/Services/Services.tsx
> +function Carousel({
컴포넌트 분리 추후 진행하고 다시 코멘트 남길게요!

2023-05-30 08:42 UTC, iihyungsuk commented on components/newHome/Services/Services.tsx
> +function Carousel({
컴포넌트 분리 완료했습니다.

2023-05-30 08:44 UTC, iihyungsuk commented
리뷰 남겨주신 내용들 모두 반영했습니다.

2023-06-16 13:10 UTC, merged