Feat/responsive activity
wafflestudio/waffledotcom-web pull request #47
Opened 2023-09-18 14:27 UTC by iihyungsuk

## 태스크 URL

## PR 체크리스트
- [ ] pre-commit 성공 여부
- [ ] Type label 추가

## Merge 체크리스트
- [ ] Squash & Merge
- [ ] 노션 태스크 완료 처리
- [ ] 이슈 코멘트 resolve

## 설명
Activity 부분 모바일 뷰 작업입니다.
현재 캐러셀 기능 남겨둔 상태입니다.

## 테스트 방법 (Optional)

## 기타 질문 및 공유 사항 (Optional)

2023-09-24 01:49 UTC, minkyu97 requested changes
고생했어~~! 언급한 부분만 조금 수정 부탁해!

2023-09-24 01:49 UTC, minkyu97 commented on components/Home/Activity/Carousel.module.scss
> +          height: 167px;
P1: 이거 고정 폭이 아니라 화면 폭에 비례해서 변했으면 좋겠어요. 예를 들어 화면 폭의 80%로 한다던가? 화면 폭이 일정 이상일 때 캐러셀이 너무 작아보이기도 하고 피그마 디자인하고 괴리가 느껴지는 듯 해서요.

2023-09-24 01:49 UTC, minkyu97 commented on styles/_responsive.scss
> +}
P3: 이건 지금 안 쓰는 것 같은데 앞으로 쓸 거 같아서 만들어 놓으신 건가요?

2023-09-24 01:49 UTC, minkyu97 commented on components/Home/Activity/Carousel.module.scss
> +        }
P1: state-n 일 때 양 옆의 이미지에는 figma에 있는 것처럼 opacity: 0.4 넣어주세요!

2023-09-24 01:52 UTC, minkyu97 commented on components/Home/Activity/Activity.tsx
> +    image: "/static/images/activity/activityImage1.png",
P1: master에 머지하기 전에 이 브랜치에 마스터 머지하실 거잖아요?? 그러면 새로 추가된 이미지들 있을텐데 그걸로 변경해주세요!

2023-09-27 06:04 UTC, iihyungsuk commented on styles/_responsive.scss
> +}
삭제했습니다!

2023-09-27 06:05 UTC, iihyungsuk commented on components/Home/Activity/Activity.tsx
> +    image: "/static/images/activity/activityImage1.png",
이거 새로 추가된 이미지를 못 찾겠습니다ㅜ figma에 있나요?

2023-09-27 06:06 UTC, minkyu97 commented on components/Home/Activity/Activity.tsx
> +    image: "/static/images/activity/activityImage1.png",
잉 develop 브랜치에 없슈???
cc. @designDefined

2023-09-27 06:09 UTC, iihyungsuk commented on components/Home/Activity/Activity.tsx
> +    image: "/static/images/activity/activityImage1.png",
아 develop 브랜치에 있구나 근데 머지하고 변경하는 게 깔끔할 거 같아요1

2023-09-27 06:10 UTC, iihyungsuk commented on components/Home/Activity/Activity.tsx
> +    image: "/static/images/activity/activityImage1.png",
아 conflict가..

2023-09-27 06:10 UTC, minkyu97 commented on components/Home/Activity/Activity.tsx
> +    image: "/static/images/activity/activityImage1.png",
ㅇㅇ 이 PR 머지하기 직전에 컨플릭 해결할 때 이미지도 교체해줘

2023-09-30 06:13 UTC, minkyu97 approved these changes
수고하셨습니다~

2023-09-30 12:56 UTC, merged