Feat/responsive home page
wafflestudio/waffledotcom-web pull request #49
Opened 2023-09-18 19:15 UTC by designDefined

## 태스크 URL

## PR 체크리스트
- [ ] pre-commit 성공 여부
- [ ] Type label 추가

## Merge 체크리스트
- [ ] Squash & Merge
- [ ] 노션 태스크 완료 처리
- [ ] 이슈 코멘트 resolve

## 설명
- 푸터는 디자인이 좀 다른데 요건 곧 반영하겠습니다.
- 홈의 메인, 어바웃, 서비스, 헤더, 푸터 반응형 처리
- px2width라는 sass 함수 만들어 사용했습니다

## 테스트 방법 (Optional)

## 기타 질문 및 공유 사항 (Optional)

2023-09-24 06:23 UTC, minkyu97 commented on components/Home/About/About.module.scss
> +@include responsive.tablet {
이거 다른 페이지랑 일관성을 위해서 tablet, mobile은 같은 ui로 가고 tablet만 크기를 좀 키우는 거 어떤가요

2023-09-24 06:29 UTC, minkyu97 requested changes
코드가 길지 않아 코멘트 몇 개만 남길게요
* 태블릿 사이즈에서 UI가 많이 잘리는데 다른 페이지와의 일관성을 위해 모바일 UI와 유사하게 가되 태블릿 사이즈에서만 UI를 1.5배 정도 확대하는 거 어떤가요? 전 em으로 작업하고 태블릿과 모바일에서 최상단 컨테이너의 font-size를 조절하니까 편하더라고요
* Header의 경우 태블릿/모바일에서 통일시키니까 태블릿 사이즈에서 크기가 너무 작은 것 같은데 태블릿 사이즈에서는 PC와 동일하되 폭만 반응형으로 줄어들고, 글자 크기 감소는 모바일에서만 하는 게 나을 거 같아요

2023-09-25 10:55 UTC, designDefined commented
__작업한 것__
- 태블릿 사이즈 모바일 ui로 수정
- 폰트 사이즈 등이 연속적으로 변화하게 수정
- 서비스탭 메인 화면 반응형 추가
- 홈 최하단의 Support 화면 반응형 수정

태블릿 사이즈 모바일 ui로 수정하고, 사이즈를 연속적으로 변화시키기 위해 _responsive.scss에 responsive-px이라는 sass 함수를 생성했습니다(feat: Add responsive-px 커밋 참고). 모바일 사이즈의 px, 데스크탑 사이즈의 px, 둘의 차이(숫자만)을 입력하면 그 사이 크기일 때의 픽셀을 계산해 줍니다.
다만 `calc` 동작 때문에 두 사이즈 사이의 diff를 숫자로 입력해주어야 하는 요상한 구조가 되었는데, 혹시 이 부분을 개선할 수 있다면 조언 부탁드립니다... css 고수님들...

@minkyu97 일단 ui적 수정사항 더 없으시면 머지하겠습니다! 리뷰 부탁

2023-09-25 11:27 UTC, minkyu97 commented on styles/_responsive.scss
> +}
이건 디자이너 요구사항인가요?? 꼭 필요하다고 하신 게 아니면 저렇게 화면 사이즈에 따라 글자 크기가 자연스럽게 필요하는 코드가 필요한지 잘 모르겠어서요... 그냥 데스크탑 UI / 태블릿 UI / 모바일 UI 경계만 변하고 글자 크기는 각 UI마다 고정하는 건 어떤가요?? 그리고 저랑 형석이도 태블릿 UI에서 글자 크기는 고정하여 작업했는데 어느쪽으로든 통일을 시켜야할 듯 합니다.

만약 저 함수가 꼭 필요하다 가정하면 diff를 따로 넣어주는 건 보기가 좀 안 좋은데 차라리 아래처럼 바꿔주는 게 좋을 것 같아요
```suggestion
@function responsive-px($min, $max) {
  @return clampValue(
    ${min}px,
    calc(${min}px + (100vw - $breakpoint-tablet) / (542 * ($max - $mix) / 1px)),
    ${max}px
  );
}
```

2023-09-25 12:04 UTC, designDefined commented on styles/_responsive.scss
> +}
아 리뷰 내용을 잘못 알아들었네요 넵 태블릿 구간 고정픽셀로 바꾸겠습니다
태블릿 ui에서 사이즈 1.5배 한 거는 임의로 설정하신 거죠? 혹시 논의된 바가 있나 해서요

2023-09-25 12:48 UTC, designDefined commented
태블릿 ui 고정픽셀로 수정완료

2023-09-25 13:25 UTC, minkyu97 commented on styles/_responsive.scss
> +}
ㄴㄴ 그냥 제 눈까리로 판단했습니다
근데 em으로 해두면 나중에 배율 바꾸는 건 엄청 쉬워서 다 완성되고 채원이랑 용재님한테 피드백 달라하면 될듯

2023-09-30 06:14 UTC, minkyu97 approved these changes
수고하셨습니다~

2023-09-30 12:56 UTC, merged